# Generated by Django 3.0.3 on 2020-05-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='tbd', max_length=20),
        ),
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default='2020-05-06'),
            preserve_default=False,
        ),
    ]
