# Generated by Django 3.0.3 on 2020-05-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200506_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='topping',
            field=models.BooleanField(default=False),
        ),
    ]
