# Generated by Django 3.0.3 on 2020-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200510_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='topping',
            field=models.IntegerField(),
        ),
    ]
