# Generated by Django 3.0.3 on 2020-05-13 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200513_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='topping',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CartItemTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.CartItem')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Topping')),
            ],
        ),
    ]
