# Generated by Django 3.0.3 on 2020-05-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200513_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='topping',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='topping1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='topping2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='topping3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.Topping'),
        ),
    ]
