# Generated by Django 3.0.3 on 2020-05-17 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_auto_20200517_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=7)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Item')),
                ('topping1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otopping1', to='orders.Topping')),
                ('topping2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otopping2', to='orders.Topping')),
                ('topping3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otopping3', to='orders.Topping')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItemTopping',
        ),
    ]
